baseurl: "/"
languageCode: "en-us"
title: "HP"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Projects
      url: "categories/"
      weight: 2
    - name: Tags
      url: "tags/"
      weight: 3
    - name: CV
      url: "https://hppersonalwebsite.com/hadrien_pistre_cv.pdf"
      weight: 4
      
params:
  description: "HP Personal Website"
  footer: "HP Personal Website {Year} - [LinkedIn](https://www.linkedin.com/in/hadrien-pistre/) | Template by &copy; Yihui Xie - [Github](https://github.com/yihui)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
