---
title: "R PROJECT | Price optimisation"
author: "HP"
date: 2022-10-02
categories: ["1. R Projects"]
tags: ["R", "Logistic regression", "Linear regression", "Price optimisation"]
---



<p>I performed this analysis on a dataset containing fictitious information about car insurance customers.</p>
<p><img src="https://hppersonalwebsite.com/car_insurance.jpg" alt="car_insurance" />
<em>Image source: <a href="https://www.dayinsure.com/news/when-does-car-insurance-get-cheaper/" target="_blank">dayinsure.com</a></em></p>
<p><strong>Used packages:</strong></p>
<pre class="r"><code>library(tidyverse)
library(dplyr)
library(readxl)
library(qpcR)
library(fastDummies)
library(janitor)
library(kableExtra)
library(GGally)
library(huxtable)
library(caret)
library(cutpointr)
library(factoextra)
library(gridExtra)
library(cluster)
library(PRROC)
library(ROCR)</code></pre>
<div id="exploring-the-data" class="section level1">
<h1>1. Exploring the data</h1>
<div id="import-the-data" class="section level2">
<h2>1.1. Import the data</h2>
<p>We start by importing into R the price data from the Excel file by fetching it from the second tab of the spreadsheet.</p>
<pre class="r"><code>#read the data from the Excel file
# insurance_data &lt;- read_excel(&quot;C:/Users/OneDrive - Pearson Ham Consulting Ltd/Desktop/R Folder/PH_training/Brief for Interview_Analyst.xlsx&quot;, sheet = 2)

insurance_data &lt;- read_excel(&quot;C:/Users/Desktop/R Folder/data/Brief for Interview_Analyst.xlsx&quot;, sheet = 2)</code></pre>
<pre><code>## New names:
## * `` -&gt; ...2
## * `` -&gt; ...3
## * `` -&gt; ...4
## * `` -&gt; ...5
## * `` -&gt; ...6
## * ...</code></pre>
<pre class="r"><code>#replace wrong colnammes with the right colnames that are on the data set&#39;s first row
colnames(insurance_data) &lt;- insurance_data[1,]

#delete the first row which is now a duplicate of the colnames
insurance_data &lt;- insurance_data[-1,]</code></pre>
</div>
<div id="format-the-data" class="section level2">
<h2>1.2. Format the data</h2>
<p>We then examine the types of data we imported.</p>
<ul>
<li>This data contains only 3 rows containing NAs out of more than 20K rows: we thus decide to delete those rows since their explanatory power is negligible given their small number.</li>
<li>Variables containing numbers are stored as characters on the original data file. We decide to convert those variables to numeric variables.</li>
<li>To be able to analyze categorical variables, we decide to create N-1 dummies for each of those variables.</li>
<li>Finally, after a qualitative examination, we conclude than only variables 7 to 9 may be colinear. We create a colinear matrix using ggpairs and determine that variables 8 and 9 are colinear; we hence decide to remove variable 9 from our dataset.</li>
</ul>
<pre><code>## tibble [20,020 x 14] (S3: tbl_df/tbl/data.frame)
##  $ Marital Status                       : chr [1:20020] &quot;M&quot; &quot;M&quot; &quot;S&quot; &quot;M&quot; ...
##  $ AGE                                  : chr [1:20020] &quot;45&quot; &quot;40&quot; &quot;25&quot; &quot;42&quot; ...
##  $ Gender                               : chr [1:20020] &quot;F&quot; &quot;M&quot; &quot;F&quot; &quot;M&quot; ...
##  $ Car Value                            : chr [1:20020] &quot;500&quot; &quot;3000&quot; &quot;4000&quot; &quot;1800&quot; ...
##  $ Years of No Claims Bonus             : chr [1:20020] &quot;4&quot; &quot;8&quot; &quot;4&quot; &quot;9&quot; ...
##  $ Annual Mileage                       : chr [1:20020] &quot;6000&quot; &quot;6000&quot; &quot;4000&quot; &quot;10000&quot; ...
##  $ Payment Method                       : chr [1:20020] &quot;Monthly&quot; &quot;Monthly&quot; &quot;Monthly&quot; &quot;Annual&quot; ...
##  $ Acquisition Channel                  : chr [1:20020] &quot;Inbound&quot; &quot;Inbound&quot; &quot;Inbound&quot; &quot;Inbound&quot; ...
##  $ Years of Tenure with Current Provider: chr [1:20020] &quot;4&quot; &quot;4&quot; &quot;4&quot; &quot;4&quot; ...
##  $ Price                                : chr [1:20020] &quot;289.35000000000002&quot; &quot;170.4&quot; &quot;466.13&quot; &quot;245.1&quot; ...
##  $ Actual Change in Price vs last Year  : chr [1:20020] &quot;-11.941498709999962&quot; &quot;45.617083578000006&quot; &quot;-123.14999999999998&quot; &quot;2.3400000000000034&quot; ...
##  $ % Change in Price vs last Year       : chr [1:20020] &quot;-3.9634369907973838E-2&quot; &quot;0.36557154525647417&quot; &quot;-0.20898384469182729&quot; &quot;9.6391497775580957E-3&quot; ...
##  $ Grouped Change in Price              : chr [1:20020] &quot;-0.05&quot; &quot;0.35&quot; &quot;-0.2&quot; &quot;0&quot; ...
##  $ Renewed?                             : chr [1:20020] &quot;0&quot; &quot;1&quot; &quot;1&quot; &quot;1&quot; ...</code></pre>
<p><table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:exploring_data">
<col><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Variable</th><th style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Number of NAs</th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Marital Status</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">AGE</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Gender</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Car Value</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Years of No Claims Bonus</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Annual Mileage</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Payment Method</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Acquisition Channel</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Years of Tenure with Current Provider</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Price</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Actual Change in Price vs last Year</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">3</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">% Change in Price vs last Year</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">3</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Grouped Change in Price</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">3</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Renewed?</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0</td></tr>
</table>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:exploring_data">
<col><col><col><col><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">marital_status</th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">gender</th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">payment_method</th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">acquisition_channel</th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">renewed</th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">M</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">F</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Monthly</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Inbound</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">S</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">M</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Annual</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Direct</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">D</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">C</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Aggreg</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;"></td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">W</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Outbound</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">V</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;"></td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;"></td></tr>
</table>
</p>
<pre><code>## tibble [20,017 x 20] (S3: tbl_df/tbl/data.frame)
##  $ age                                  : num [1:20017] 45 40 25 42 59 54 39 29 25 33 ...
##  $ car_value                            : num [1:20017] 500 3000 4000 1800 5000 2500 300 800 800 1000 ...
##  $ years_of_no_claims_bonus             : num [1:20017] 4 8 4 9 9 6 9 9 3 6 ...
##  $ annual_mileage                       : num [1:20017] 6000 6000 4000 10000 3000 3000 10000 7000 5000 8000 ...
##  $ years_of_tenure_with_current_provider: num [1:20017] 4 4 4 4 4 4 4 4 4 4 ...
##  $ price                                : num [1:20017] 289 170 466 245 240 ...
##  $ actual_change_in_price_vs_last_year  : num [1:20017] -11.94 45.62 -123.15 2.34 42.56 ...
##  $ percent_change_in_price_vs_last_year : num [1:20017] -0.03963 0.36557 -0.20898 0.00964 0.21501 ...
##  $ grouped_change_in_price              : num [1:20017] -0.05 0.35 -0.2 0 0.2 0.05 0 0.35 -0.25 -0.05 ...
##  $ renewed                              : num [1:20017] 0 1 1 1 0 0 1 1 0 1 ...
##  $ marital_status_d                     : num [1:20017] 0 0 0 0 0 0 0 0 0 0 ...
##  $ marital_status_m                     : num [1:20017] 1 1 0 1 1 1 1 1 0 0 ...
##  $ marital_status_s                     : num [1:20017] 0 0 1 0 0 0 0 0 1 1 ...
##  $ marital_status_v                     : num [1:20017] 0 0 0 0 0 0 0 0 0 0 ...
##  $ gender_f                             : num [1:20017] 1 0 1 0 0 1 1 0 0 0 ...
##  $ gender_m                             : num [1:20017] 0 1 0 1 1 0 0 1 1 1 ...
##  $ payment_method_annual                : num [1:20017] 0 0 0 1 1 1 0 0 0 1 ...
##  $ acquisition_channel_aggreg           : num [1:20017] 0 0 0 0 0 0 0 0 0 0 ...
##  $ acquisition_channel_direct           : num [1:20017] 0 0 0 0 0 0 0 0 0 0 ...
##  $ acquisition_channel_inbound          : num [1:20017] 1 1 1 1 1 1 1 1 1 1 ...
##  - attr(*, &quot;na.action&quot;)= &#39;omit&#39; Named int [1:3] 6544 7369 9082
##   ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;6544&quot; &quot;7369&quot; &quot;9082&quot;
##  - attr(*, &quot;.internal.selfref&quot;)=&lt;externalptr&gt;</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/exploring_data-1.png" width="672" /></p>
</div>
</div>
<div id="analyse-the-factors-that-drive-price" class="section level1">
<h1>2. Analyse the factors that drive price</h1>
<div id="vizualise-the-data" class="section level2">
<h2>2.1. Vizualise the data</h2>
<div id="examine-distributions" class="section level3">
<h3>2.1.1. Examine distributions</h3>
<p>We want to visualize the individual impact of each variable on price. We first plot the distribution of all non-dummy variables to examine if they contain outliers that could make our data visualization less relevant.</p>
<pre class="r"><code>#create histograms of each non-dummy variable

#price
ggplot(insurance_data_dummied_short, aes(x=price))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Price&quot;,y=&quot;Count&quot;,title=&quot;Price distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20distribution-1.png" width="672" /></p>
<pre class="r"><code>#age
ggplot(insurance_data_dummied_short, aes(x=age))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Age&quot;,y=&quot;Count&quot;,title=&quot;Age distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20distribution-2.png" width="672" /></p>
<pre class="r"><code>#car value
ggplot(insurance_data_dummied_short, aes(x=car_value))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Car value&quot;,y=&quot;Count&quot;,title=&quot;Car value distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20distribution-3.png" width="672" /></p>
<pre class="r"><code>#years of no claim bonus
ggplot(insurance_data_dummied_short, aes(x=years_of_no_claims_bonus))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Years of no claim bonus&quot;,y=&quot;Count&quot;,title=&quot;Years of no claim bonus distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20distribution-4.png" width="672" /></p>
<pre class="r"><code>#annual mileage
ggplot(insurance_data_dummied_short, aes(x=annual_mileage))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Annual mileage&quot;,y=&quot;Count&quot;,title=&quot;Annual mileage distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20distribution-5.png" width="672" /></p>
<pre class="r"><code>#year of tenure with current provider
ggplot(insurance_data_dummied_short, aes(x=years_of_tenure_with_current_provider))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Years of tenure with current provider&quot;,y=&quot;Count&quot;,title=&quot;Years of tenure with current provider distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20distribution-6.png" width="672" /></p>
<pre class="r"><code>#actual change in price vs. last year
ggplot(insurance_data_dummied_short, aes(x=actual_change_in_price_vs_last_year))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Actual change in price vs. last year&quot;,y=&quot;Count&quot;,title=&quot;Actual change in price vs. last year distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20distribution-7.png" width="672" /></p>
<pre class="r"><code>#percent change in price vs last year
ggplot(insurance_data_dummied_short, aes(x=percent_change_in_price_vs_last_year))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Percent change in price vs. last year&quot;,y=&quot;Count&quot;,title=&quot;Percent change in price vs. last year distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20distribution-8.png" width="672" /></p>
</div>
<div id="examine-distributions-without-outliers" class="section level3">
<h3>2.1.2. Examine distributions without outliers</h3>
<p>We notice that the variables “Car value”, “Annual mileage distribution”, “Actual change in price vs. last year” and “Percent change in price vs. last year” contain significant outliers. We get rid of the last percentile of the first two variables and of the first and last percentiles of the last two variables to vizualise them properly. We notice that this greatly improve the visualization of their distribution.</p>
<pre class="r"><code>#get rid of the extreme percentiles to improve our data visualization
insurance_data_dummied_short_no_outliers &lt;- insurance_data_dummied_short %&gt;%
  subset(car_value &lt; quantile(car_value, 0.99)
         &amp; annual_mileage &lt; quantile(annual_mileage, 0.99)
         &amp; actual_change_in_price_vs_last_year &lt; quantile(actual_change_in_price_vs_last_year, 0.99)
         &amp; actual_change_in_price_vs_last_year &gt; quantile(actual_change_in_price_vs_last_year, 0.01)
         &amp; percent_change_in_price_vs_last_year &lt; quantile(percent_change_in_price_vs_last_year, 0.99)
         &amp; percent_change_in_price_vs_last_year &gt; quantile(percent_change_in_price_vs_last_year, 0.01))

#create histograms of each non-dummy variable to re-examine them

#price
ggplot(insurance_data_dummied_short_no_outliers, aes(x=price))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Price&quot;,y=&quot;Count&quot;,title=&quot;Price distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/delete%20outliers%20and%20reeaxmine%20distribution-1.png" width="672" /></p>
<pre class="r"><code>#age
ggplot(insurance_data_dummied_short_no_outliers, aes(x=age))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Age&quot;,y=&quot;Count&quot;,title=&quot;Age distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/delete%20outliers%20and%20reeaxmine%20distribution-2.png" width="672" /></p>
<pre class="r"><code>#car value
ggplot(insurance_data_dummied_short_no_outliers, aes(x=car_value))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Car value&quot;,y=&quot;Count&quot;,title=&quot;Car value distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/delete%20outliers%20and%20reeaxmine%20distribution-3.png" width="672" /></p>
<pre class="r"><code>#years of no claim bonus
ggplot(insurance_data_dummied_short_no_outliers, aes(x=years_of_no_claims_bonus))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Years of no claim bonus&quot;,y=&quot;Count&quot;,title=&quot;Years of no claim bonus distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/delete%20outliers%20and%20reeaxmine%20distribution-4.png" width="672" /></p>
<pre class="r"><code>#annual mileage
ggplot(insurance_data_dummied_short_no_outliers, aes(x=annual_mileage))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Annual mileage&quot;,y=&quot;Count&quot;,title=&quot;Annual mileage distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/delete%20outliers%20and%20reeaxmine%20distribution-5.png" width="672" /></p>
<pre class="r"><code>#years of tenure with current provider
ggplot(insurance_data_dummied_short_no_outliers, aes(x=years_of_tenure_with_current_provider))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Years of tenure with current provider&quot;,y=&quot;Count&quot;,title=&quot;Years of tenure with current provider distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/delete%20outliers%20and%20reeaxmine%20distribution-6.png" width="672" /></p>
<pre class="r"><code>#actual change in price vs. last year
ggplot(insurance_data_dummied_short_no_outliers, aes(x=actual_change_in_price_vs_last_year))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Actual change in price vs. last year&quot;,y=&quot;Count&quot;,title=&quot;Actual change in price vs. last year distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/delete%20outliers%20and%20reeaxmine%20distribution-7.png" width="672" /></p>
<pre class="r"><code>#percent change in price vs. last year
ggplot(insurance_data_dummied_short_no_outliers, aes(x=percent_change_in_price_vs_last_year))+
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  theme_bw()+
  labs(x=&quot;Percent change in price vs. last year&quot;,y=&quot;Count&quot;,title=&quot;Percent change in price vs. last year distribution&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/delete%20outliers%20and%20reeaxmine%20distribution-8.png" width="672" /></p>
</div>
<div id="vizualise-the-individual-effect-of-each-variable-on-price" class="section level3">
<h3>2.1.3. Vizualise the individual effect of each variable on price</h3>
<p>Now that outliers have been removed, we can visualize the individual impact of each non-dummy variable on price.</p>
<pre class="r"><code>#create scatter plots using ggplot and add a trend line to examine the impact of each variable on price

#price vs age
ggplot(insurance_data_dummied_short_no_outliers, aes(y=price,x=age))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(title=&quot;Price vs. Age&quot;,x=&quot;Age&quot;,y=&quot;Price&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20impact%20of%20each%20variable%20on%20price-1.png" width="672" /></p>
<pre class="r"><code>#price vs car value
ggplot(insurance_data_dummied_short_no_outliers, aes(y=price,x=car_value))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(title=&quot;Price vs. Car value&quot;,x=&quot;Car value&quot;,y=&quot;Price&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20impact%20of%20each%20variable%20on%20price-2.png" width="672" /></p>
<pre class="r"><code>#price vs years of no claim bonus
ggplot(insurance_data_dummied_short_no_outliers, aes(y=price,x=years_of_no_claims_bonus))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(title=&quot;Price vs. Years of no claims bonus&quot;,x=&quot;Years of no claims bonus&quot;,y=&quot;Price&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20impact%20of%20each%20variable%20on%20price-3.png" width="672" /></p>
<pre class="r"><code>#price vs annual mileage
ggplot(insurance_data_dummied_short_no_outliers, aes(y=price,x=annual_mileage))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(title=&quot;Price vs. Annual mileage&quot;,x=&quot;Annual mileage&quot;,y=&quot;Price&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20impact%20of%20each%20variable%20on%20price-4.png" width="672" /></p>
<pre class="r"><code>#price vs years of tenure with current provider
ggplot(insurance_data_dummied_short_no_outliers, aes(y=price,x=years_of_tenure_with_current_provider))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(title=&quot;Price vs. Years of tenure with current provider&quot;,x=&quot;Years of tenure with current provider&quot;,y=&quot;Price&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<pre><code>## Warning: Computation failed in `stat_smooth()`:
## x has insufficient unique values to support 10 knots: reduce k.</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20impact%20of%20each%20variable%20on%20price-5.png" width="672" /></p>
<pre class="r"><code>#price vs actual change in price vs last year
ggplot(insurance_data_dummied_short_no_outliers, aes(y=price,x=actual_change_in_price_vs_last_year))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(title=&quot;Price vs. Actual change in price vs. last year&quot;,x=&quot;Actual change in price vs last year&quot;,y=&quot;Price&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20impact%20of%20each%20variable%20on%20price-6.png" width="672" /></p>
<pre class="r"><code>#price vs percent change in price vs last year
ggplot(insurance_data_dummied_short_no_outliers, aes(y=price,x=percent_change_in_price_vs_last_year))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;)+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5))+
  labs(title=&quot;Price vs. Percent change in price vs. last year&quot;,x=&quot;Percent change in price vs. last year&quot;,y=&quot;Price&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/examine%20impact%20of%20each%20variable%20on%20price-7.png" width="672" /></p>
</div>
</div>
<div id="analyse-the-data-and-create-linear-regression-models-to-predict-the-price" class="section level2">
<h2>2.2. Analyse the data and create linear regression models to predict the price</h2>
<div id="create-the-models" class="section level3">
<h3>2.2.1. Create the models</h3>
<p>Thanks to our data visualization above, we notice that an increase in the annual change in price vs last year has a negative impact on price when it is negative, and a positive impact on price when it is positive. This means that creating two linear regression models - one used when the actual change in price vs last year is negative, and one when it is positive - could yield a better result than create one linear regression model without any discrimination.</p>
<p>The effects of the other variables on price seem linear, therefore it is unlikely that further subsetting our data based on the other variables would improve the predictive power of our model.</p>
<p>To examine if we can obtain better results using two models rather than one, we first create a linear regression model using all the statistically significant variables at a <strong>95%</strong> confidence interval (=&gt; with a t-stat greater than <strong>1.96</strong>).</p>
<div id="linear-regression" class="section level4">
<h4>Linear regression</h4>
<p><em>Note: we get rid of the non statistically significant variables</em></p>
<pre class="r"><code>#let us create a linear regression model for price using all non-dummy variables
lin_reg_full &lt;- lm(price ~ 
                  age+
                  car_value+
                  years_of_no_claims_bonus+
                  annual_mileage+
                  years_of_tenure_with_current_provider+
                  actual_change_in_price_vs_last_year+
                  percent_change_in_price_vs_last_year+
                  renewed+
                  marital_status_d+
                  marital_status_m+
                  marital_status_s+
                  marital_status_v+
                  gender_f+
                  gender_m+
                  payment_method_annual+
                  acquisition_channel_aggreg+
                  acquisition_channel_direct+
                  acquisition_channel_inbound,
                data = insurance_data_dummied_short)
summary(lin_reg_full)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ age + car_value + years_of_no_claims_bonus + 
##     annual_mileage + years_of_tenure_with_current_provider + 
##     actual_change_in_price_vs_last_year + percent_change_in_price_vs_last_year + 
##     renewed + marital_status_d + marital_status_m + marital_status_s + 
##     marital_status_v + gender_f + gender_m + payment_method_annual + 
##     acquisition_channel_aggreg + acquisition_channel_direct + 
##     acquisition_channel_inbound, data = insurance_data_dummied_short)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2638.3  -119.0   -34.4    65.2  3404.7 
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                            8.573e+02  1.360e+02   6.304 2.96e-10
## age                                   -4.099e+00  1.516e-01 -27.045  &lt; 2e-16
## car_value                              1.509e-02  4.053e-04  37.223  &lt; 2e-16
## years_of_no_claims_bonus              -3.071e+01  5.808e-01 -52.881  &lt; 2e-16
## annual_mileage                        -2.051e-04  4.437e-04  -0.462    0.644
## years_of_tenure_with_current_provider -1.370e+01  1.839e+00  -7.449 9.77e-14
## actual_change_in_price_vs_last_year    9.680e-02  3.762e-03  25.734  &lt; 2e-16
## percent_change_in_price_vs_last_year   2.344e+00  4.816e-01   4.866 1.15e-06
## renewed                               -7.082e+01  3.259e+00 -21.734  &lt; 2e-16
## marital_status_d                      -7.707e+01  1.182e+01  -6.523 7.07e-11
## marital_status_m                      -6.337e+01  1.077e+01  -5.882 4.13e-09
## marital_status_s                      -4.631e+01  1.125e+01  -4.118 3.84e-05
## marital_status_v                      -1.065e+02  2.616e+01  -4.071 4.70e-05
## gender_f                              -5.186e+01  4.887e+01  -1.061    0.289
## gender_m                               1.632e+01  4.884e+01   0.334    0.738
## payment_method_annual                 -6.030e+01  3.786e+00 -15.925  &lt; 2e-16
## acquisition_channel_aggreg             7.359e+01  1.407e+02   0.523    0.601
## acquisition_channel_direct             7.417e+00  1.260e+02   0.059    0.953
## acquisition_channel_inbound            4.221e+01  1.259e+02   0.335    0.737
##                                          
## (Intercept)                           ***
## age                                   ***
## car_value                             ***
## years_of_no_claims_bonus              ***
## annual_mileage                           
## years_of_tenure_with_current_provider ***
## actual_change_in_price_vs_last_year   ***
## percent_change_in_price_vs_last_year  ***
## renewed                               ***
## marital_status_d                      ***
## marital_status_m                      ***
## marital_status_s                      ***
## marital_status_v                      ***
## gender_f                                 
## gender_m                                 
## payment_method_annual                 ***
## acquisition_channel_aggreg               
## acquisition_channel_direct               
## acquisition_channel_inbound              
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 218 on 19998 degrees of freedom
## Multiple R-squared:  0.3106, Adjusted R-squared:   0.31 
## F-statistic: 500.7 on 18 and 19998 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#we remove one by one variables with absolute t-values &lt;2 starting with the smallest: acquisition_channel_direct, gender_m, annual_mileage and acquisition_channel_aggreg
lin_reg_sig &lt;- lm(price ~ 
                  age+
                  car_value+
                  years_of_no_claims_bonus+
                  years_of_tenure_with_current_provider+
                  actual_change_in_price_vs_last_year+
                  percent_change_in_price_vs_last_year+
                  renewed+
                  marital_status_d+
                  marital_status_m+
                  marital_status_s+
                  marital_status_v+
                  gender_f+
                  payment_method_annual+
                  acquisition_channel_inbound,
                data = insurance_data_dummied_short)
summary(lin_reg_sig)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ age + car_value + years_of_no_claims_bonus + 
##     years_of_tenure_with_current_provider + actual_change_in_price_vs_last_year + 
##     percent_change_in_price_vs_last_year + renewed + marital_status_d + 
##     marital_status_m + marital_status_s + marital_status_v + 
##     gender_f + payment_method_annual + acquisition_channel_inbound, 
##     data = insurance_data_dummied_short)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2638.0  -119.2   -34.5    65.1  3405.2 
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                            8.797e+02  1.498e+01  58.711  &lt; 2e-16
## age                                   -4.096e+00  1.511e-01 -27.107  &lt; 2e-16
## car_value                              1.506e-02  3.977e-04  37.865  &lt; 2e-16
## years_of_no_claims_bonus              -3.072e+01  5.800e-01 -52.963  &lt; 2e-16
## years_of_tenure_with_current_provider -1.361e+01  1.836e+00  -7.413 1.29e-13
## actual_change_in_price_vs_last_year    9.678e-02  3.761e-03  25.735  &lt; 2e-16
## percent_change_in_price_vs_last_year   2.344e+00  4.816e-01   4.868 1.14e-06
## renewed                               -7.078e+01  3.257e+00 -21.733  &lt; 2e-16
## marital_status_d                      -7.714e+01  1.180e+01  -6.534 6.55e-11
## marital_status_m                      -6.348e+01  1.076e+01  -5.898 3.74e-09
## marital_status_s                      -4.640e+01  1.124e+01  -4.129 3.67e-05
## marital_status_v                      -1.068e+02  2.616e+01  -4.081 4.49e-05
## gender_f                              -6.798e+01  3.184e+00 -21.352  &lt; 2e-16
## payment_method_annual                 -6.012e+01  3.782e+00 -15.896  &lt; 2e-16
## acquisition_channel_inbound            3.456e+01  3.939e+00   8.773  &lt; 2e-16
##                                          
## (Intercept)                           ***
## age                                   ***
## car_value                             ***
## years_of_no_claims_bonus              ***
## years_of_tenure_with_current_provider ***
## actual_change_in_price_vs_last_year   ***
## percent_change_in_price_vs_last_year  ***
## renewed                               ***
## marital_status_d                      ***
## marital_status_m                      ***
## marital_status_s                      ***
## marital_status_v                      ***
## gender_f                              ***
## payment_method_annual                 ***
## acquisition_channel_inbound           ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 218 on 20002 degrees of freedom
## Multiple R-squared:  0.3106, Adjusted R-squared:  0.3101 
## F-statistic: 643.7 on 14 and 20002 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="linear-regression-with-interaction-terms" class="section level4">
<h4>Linear regression with interaction terms</h4>
<p>We now create a linear regression with interaction terms that account for the sign (&lt;0 or &gt;0) of the actual change in price vs. last year by creeating two columns.</p>
<pre class="r"><code>#create a column which takes the value of the actual change in price if this change is positive, and zero otherwise
insurance_data_dummied_short$actual_change_in_price_vs_last_year_pos &lt;- insurance_data_dummied_short$actual_change_in_price_vs_last_year
insurance_data_dummied_short$actual_change_in_price_vs_last_year_pos[insurance_data_dummied_short$actual_change_in_price_vs_last_year_pos&lt;0] &lt;- &quot;0&quot;
insurance_data_dummied_short$actual_change_in_price_vs_last_year_pos &lt;- as.numeric(insurance_data_dummied_short$actual_change_in_price_vs_last_year_pos)

#create a column which takes the value of the actual change in price if this change is strictly negative, and zero otherwise
insurance_data_dummied_short$actual_change_in_price_vs_last_year_neg &lt;- insurance_data_dummied_short$actual_change_in_price_vs_last_year
insurance_data_dummied_short$actual_change_in_price_vs_last_year_neg[insurance_data_dummied_short$actual_change_in_price_vs_last_year_neg&gt;=0] &lt;- &quot;0&quot;
insurance_data_dummied_short$actual_change_in_price_vs_last_year_neg &lt;- as.numeric(insurance_data_dummied_short$actual_change_in_price_vs_last_year_neg)

#run our linear regression with the interaction terms (we remove the variable of actual change in price since this data is now encompassed in our new two interaction terms)
lin_reg_act_pric_disc &lt;- lm(price ~ 
                  age+
                  car_value+
                  years_of_no_claims_bonus+
                  years_of_tenure_with_current_provider+
                  percent_change_in_price_vs_last_year+
                  renewed+
                  marital_status_d+
                  marital_status_m+
                  marital_status_s+
                  marital_status_v+
                  gender_f+
                  payment_method_annual+
                  acquisition_channel_inbound+
                  actual_change_in_price_vs_last_year_pos+
                  actual_change_in_price_vs_last_year_neg,
                data = insurance_data_dummied_short)
summary(lin_reg_act_pric_disc)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ age + car_value + years_of_no_claims_bonus + 
##     years_of_tenure_with_current_provider + percent_change_in_price_vs_last_year + 
##     renewed + marital_status_d + marital_status_m + marital_status_s + 
##     marital_status_v + gender_f + payment_method_annual + acquisition_channel_inbound + 
##     actual_change_in_price_vs_last_year_pos + actual_change_in_price_vs_last_year_neg, 
##     data = insurance_data_dummied_short)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5774.8  -114.3   -32.2    63.6  3263.3 
## 
## Coefficients:
##                                           Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                              8.460e+02  1.470e+01  57.551  &lt; 2e-16
## age                                     -3.930e+00  1.479e-01 -26.566  &lt; 2e-16
## car_value                                1.437e-02  3.898e-04  36.878  &lt; 2e-16
## years_of_no_claims_bonus                -2.911e+01  5.699e-01 -51.080  &lt; 2e-16
## years_of_tenure_with_current_provider   -1.372e+01  1.796e+00  -7.640 2.26e-14
## percent_change_in_price_vs_last_year     2.334e+00  4.711e-01   4.953 7.37e-07
## renewed                                 -6.580e+01  3.190e+00 -20.625  &lt; 2e-16
## marital_status_d                        -7.615e+01  1.155e+01  -6.594 4.40e-11
## marital_status_m                        -6.032e+01  1.053e+01  -5.728 1.03e-08
## marital_status_s                        -4.228e+01  1.100e+01  -3.845 0.000121
## marital_status_v                        -9.884e+01  2.559e+01  -3.862 0.000113
## gender_f                                -6.616e+01  3.115e+00 -21.237  &lt; 2e-16
## payment_method_annual                   -5.893e+01  3.700e+00 -15.924  &lt; 2e-16
## acquisition_channel_inbound              3.543e+01  3.853e+00   9.195  &lt; 2e-16
## actual_change_in_price_vs_last_year_pos  1.821e-01  4.651e-03  39.154  &lt; 2e-16
## actual_change_in_price_vs_last_year_neg -5.784e-02  6.334e-03  -9.131  &lt; 2e-16
##                                            
## (Intercept)                             ***
## age                                     ***
## car_value                               ***
## years_of_no_claims_bonus                ***
## years_of_tenure_with_current_provider   ***
## percent_change_in_price_vs_last_year    ***
## renewed                                 ***
## marital_status_d                        ***
## marital_status_m                        ***
## marital_status_s                        ***
## marital_status_v                        ***
## gender_f                                ***
## payment_method_annual                   ***
## acquisition_channel_inbound             ***
## actual_change_in_price_vs_last_year_pos ***
## actual_change_in_price_vs_last_year_neg ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 213.2 on 20001 degrees of freedom
## Multiple R-squared:  0.3403, Adjusted R-squared:  0.3398 
## F-statistic: 687.7 on 15 and 20001 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We observe that we obtain adjusted R-squared of <strong>0.3398</strong> when we add two interaction terms to discriminate for the sign (&lt;0 or &gt;0) of the actual change in price vs. last year, vs <strong>0.3101</strong> when we do not.</p>
</div>
</div>
<div id="backtest-the-models" class="section level3">
<h3>2.2.2. Backtest the models</h3>
<p>We now want to back test our models to see if disriminating based on the change in actual price indeed yields better results. We train our models on a random sample of <strong>60%</strong> of the data, and test it on the remaining <strong>40%</strong>.</p>
<div id="linear-regression-back-testing" class="section level4">
<h4>Linear regression back-testing</h4>
<pre class="r"><code>#define the sample size
smp_size &lt;- floor(0.6 * nrow(insurance_data_dummied_short))
set.seed(123)
train_ind &lt;- sample(seq_len(nrow(insurance_data_dummied_short)), size = smp_size)

#breakdown our data in a training and a testing sets
insurance_data_dummied_short_train &lt;- insurance_data_dummied_short[train_ind, ]
insurance_data_dummied_short_test &lt;- insurance_data_dummied_short[-train_ind, ]

#train our model
lin_reg_sig_trained &lt;- lm(price ~ 
                  age+
                  car_value+
                  years_of_no_claims_bonus+
                  years_of_tenure_with_current_provider+
                  actual_change_in_price_vs_last_year+
                  percent_change_in_price_vs_last_year+
                  renewed+
                  marital_status_d+
                  marital_status_m+
                  marital_status_s+
                  marital_status_v+
                  gender_f+
                  payment_method_annual+
                  acquisition_channel_inbound,
                data = insurance_data_dummied_short_train)
summary(lin_reg_sig_trained)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ age + car_value + years_of_no_claims_bonus + 
##     years_of_tenure_with_current_provider + actual_change_in_price_vs_last_year + 
##     percent_change_in_price_vs_last_year + renewed + marital_status_d + 
##     marital_status_m + marital_status_s + marital_status_v + 
##     gender_f + payment_method_annual + acquisition_channel_inbound, 
##     data = insurance_data_dummied_short_train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2392.9  -119.0   -35.1    61.9  3201.5 
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                            8.936e+02  1.923e+01  46.476  &lt; 2e-16
## age                                   -4.265e+00  1.956e-01 -21.805  &lt; 2e-16
## car_value                              1.528e-02  5.147e-04  29.683  &lt; 2e-16
## years_of_no_claims_bonus              -3.070e+01  7.500e-01 -40.927  &lt; 2e-16
## years_of_tenure_with_current_provider -1.552e+01  2.386e+00  -6.507 7.96e-11
## actual_change_in_price_vs_last_year    1.866e-01  7.012e-03  26.610  &lt; 2e-16
## percent_change_in_price_vs_last_year   1.182e+00  4.902e-01   2.412 0.015864
## renewed                               -6.870e+01  4.225e+00 -16.260  &lt; 2e-16
## marital_status_d                      -8.090e+01  1.508e+01  -5.365 8.25e-08
## marital_status_m                      -6.821e+01  1.370e+01  -4.978 6.52e-07
## marital_status_s                      -5.340e+01  1.433e+01  -3.727 0.000195
## marital_status_v                      -1.487e+02  3.462e+01  -4.295 1.76e-05
## gender_f                              -6.788e+01  4.120e+00 -16.475  &lt; 2e-16
## payment_method_annual                 -6.106e+01  4.889e+00 -12.491  &lt; 2e-16
## acquisition_channel_inbound            3.600e+01  5.095e+00   7.065 1.70e-12
##                                          
## (Intercept)                           ***
## age                                   ***
## car_value                             ***
## years_of_no_claims_bonus              ***
## years_of_tenure_with_current_provider ***
## actual_change_in_price_vs_last_year   ***
## percent_change_in_price_vs_last_year  *  
## renewed                               ***
## marital_status_d                      ***
## marital_status_m                      ***
## marital_status_s                      ***
## marital_status_v                      ***
## gender_f                              ***
## payment_method_annual                 ***
## acquisition_channel_inbound           ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 218.7 on 11995 degrees of freedom
## Multiple R-squared:  0.3239, Adjusted R-squared:  0.3231 
## F-statistic: 410.5 on 14 and 11995 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#test our model
lin_reg_sig_tested_data &lt;- data.frame(predict(lin_reg_sig_trained, newdata = insurance_data_dummied_short_test))
lin_reg_sig_tested_vs_reality &lt;- cbind(lin_reg_sig_tested_data,insurance_data_dummied_short_test$price)
colnames(lin_reg_sig_tested_vs_reality) &lt;- c(&quot;predicted&quot;,&quot;reality&quot;)

#compute the mean squared error and the mean absolute error
lin_reg_sig_tested_vs_reality$squared_error &lt;- (lin_reg_sig_tested_vs_reality$predicted - lin_reg_sig_tested_vs_reality$reality)^2
lin_reg_sig_tested_vs_reality$absolute_error &lt;- abs((lin_reg_sig_tested_vs_reality$predicted - lin_reg_sig_tested_vs_reality$reality))
lin_reg_sig_tested_vs_reality$absolute_error_perc &lt;- abs(((lin_reg_sig_tested_vs_reality$predicted - lin_reg_sig_tested_vs_reality$reality))/lin_reg_sig_tested_vs_reality$predicted)*100
mse_lin_reg_sig = mean(lin_reg_sig_tested_vs_reality$squared_error)
mae_lin_reg_sig = mean(lin_reg_sig_tested_vs_reality$absolute_error)
mape_lin_reg_sig = mean(lin_reg_sig_tested_vs_reality$absolute_error_perc)
mse_lin_reg_sig</code></pre>
<pre><code>## [1] 50453.13</code></pre>
<pre class="r"><code>mae_lin_reg_sig</code></pre>
<pre><code>## [1] 136.5454</code></pre>
<pre class="r"><code>mape_lin_reg_sig</code></pre>
<pre><code>## [1] 33.59408</code></pre>
</div>
<div id="linear-regression-with-interaction-terms-back-testing" class="section level4">
<h4>Linear regression with interaction terms back-testing</h4>
<pre class="r"><code>#train our model
lin_reg_act_pric_disc_trained &lt;- lm(price ~ 
                  age+
                  car_value+
                  years_of_no_claims_bonus+
                  years_of_tenure_with_current_provider+
                  percent_change_in_price_vs_last_year+
                  renewed+
                  marital_status_d+
                  marital_status_m+
                  marital_status_s+
                  marital_status_v+
                  gender_f+
                  payment_method_annual+
                  acquisition_channel_inbound+
                  actual_change_in_price_vs_last_year_pos+
                  actual_change_in_price_vs_last_year_neg,
                data = insurance_data_dummied_short_train)
summary(lin_reg_act_pric_disc_trained)</code></pre>
<pre><code>## 
## Call:
## lm(formula = price ~ age + car_value + years_of_no_claims_bonus + 
##     years_of_tenure_with_current_provider + percent_change_in_price_vs_last_year + 
##     renewed + marital_status_d + marital_status_m + marital_status_s + 
##     marital_status_v + gender_f + payment_method_annual + acquisition_channel_inbound + 
##     actual_change_in_price_vs_last_year_pos + actual_change_in_price_vs_last_year_neg, 
##     data = insurance_data_dummied_short_train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6604.5  -106.3   -28.8    60.1  3120.1 
## 
## Coefficients:
##                                           Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                              8.091e+02  1.812e+01  44.657  &lt; 2e-16
## age                                     -3.923e+00  1.833e-01 -21.404  &lt; 2e-16
## car_value                                1.390e-02  4.830e-04  28.786  &lt; 2e-16
## years_of_no_claims_bonus                -2.673e+01  7.088e-01 -37.719  &lt; 2e-16
## years_of_tenure_with_current_provider   -1.470e+01  2.234e+00  -6.581 4.86e-11
## percent_change_in_price_vs_last_year     7.335e-01  4.590e-01   1.598  0.11009
## renewed                                 -5.690e+01  3.966e+00 -14.346  &lt; 2e-16
## marital_status_d                        -7.220e+01  1.412e+01  -5.114 3.21e-07
## marital_status_m                        -6.151e+01  1.283e+01  -4.794 1.66e-06
## marital_status_s                        -4.344e+01  1.342e+01  -3.238  0.00121
## marital_status_v                        -1.301e+02  3.242e+01  -4.015 5.99e-05
## gender_f                                -6.224e+01  3.860e+00 -16.124  &lt; 2e-16
## payment_method_annual                   -5.985e+01  4.577e+00 -13.077  &lt; 2e-16
## acquisition_channel_inbound              3.951e+01  4.771e+00   8.282  &lt; 2e-16
## actual_change_in_price_vs_last_year_pos  4.515e-01  9.197e-03  49.090  &lt; 2e-16
## actual_change_in_price_vs_last_year_neg -1.339e-01  1.019e-02 -13.143  &lt; 2e-16
##                                            
## (Intercept)                             ***
## age                                     ***
## car_value                               ***
## years_of_no_claims_bonus                ***
## years_of_tenure_with_current_provider   ***
## percent_change_in_price_vs_last_year       
## renewed                                 ***
## marital_status_d                        ***
## marital_status_m                        ***
## marital_status_s                        ** 
## marital_status_v                        ***
## gender_f                                ***
## payment_method_annual                   ***
## acquisition_channel_inbound             ***
## actual_change_in_price_vs_last_year_pos ***
## actual_change_in_price_vs_last_year_neg ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 204.8 on 11994 degrees of freedom
## Multiple R-squared:  0.4075, Adjusted R-squared:  0.4067 
## F-statistic: 549.8 on 15 and 11994 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#test our model
lin_reg_act_pric_disc_tested_data &lt;- data.frame(predict(lin_reg_act_pric_disc_trained, newdata = insurance_data_dummied_short_test))
lin_reg_act_pric_disc_tested_vs_reality &lt;- cbind(lin_reg_act_pric_disc_tested_data,insurance_data_dummied_short_test$price)
colnames(lin_reg_act_pric_disc_tested_vs_reality) &lt;- c(&quot;predicted&quot;,&quot;reality&quot;)

#compute the mean squared error and the mean absolute error
lin_reg_act_pric_disc_tested_vs_reality$squared_error &lt;- (lin_reg_act_pric_disc_tested_vs_reality$predicted - lin_reg_act_pric_disc_tested_vs_reality$reality)^2
lin_reg_act_pric_disc_tested_vs_reality$absolute_error &lt;- abs((lin_reg_act_pric_disc_tested_vs_reality$predicted - lin_reg_act_pric_disc_tested_vs_reality$reality))
lin_reg_act_pric_disc_tested_vs_reality$absolute_error_perc &lt;- abs(((lin_reg_act_pric_disc_tested_vs_reality$predicted - lin_reg_act_pric_disc_tested_vs_reality$reality))/lin_reg_act_pric_disc_tested_vs_reality$predicted)*100
mse_lin_reg_act_pric_disc = mean(lin_reg_act_pric_disc_tested_vs_reality$squared_error)
mae_lin_reg_act_pric_disc = mean(lin_reg_act_pric_disc_tested_vs_reality$absolute_error)
mape_lin_reg_act_pric_disc = mean(lin_reg_act_pric_disc_tested_vs_reality$absolute_error_perc)
mse_lin_reg_act_pric_disc</code></pre>
<pre><code>## [1] 70449.54</code></pre>
<pre class="r"><code>mae_lin_reg_act_pric_disc</code></pre>
<pre><code>## [1] 126.7465</code></pre>
<pre class="r"><code>mape_lin_reg_act_pric_disc</code></pre>
<pre><code>## [1] 29.73929</code></pre>
</div>
</div>
<div id="compare-our-models" class="section level3">
<h3>2.2.3. Compare our models</h3>
<p>Now that we backtested our linear regression models, we can compare them.</p>
<pre class="r"><code>#compare the 4 models we ran: the 2 linear regressions ran on the full sample and their back-tested versions
huxreg(lin_reg_sig, lin_reg_act_pric_disc, lin_reg_sig_trained, lin_reg_act_pric_disc_trained)</code></pre>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:comparison of linear regressions">
<col><col><col><col><col><tr>
<th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1)</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(2)</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3)</th><th style="vertical-align: top; text-align: center; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(4)</th></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(Intercept)</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">879.654 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">846.011 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">893.624 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">809.102 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(14.983)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(14.700)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(19.228)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(18.118)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">age</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-4.096 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-3.930 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-4.265 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-3.923 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.151)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.148)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.196)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.183)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">car_value</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.015 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.014 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.015 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.014 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.001)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.000)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">years_of_no_claims_bonus</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-30.719 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-29.112 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-30.697 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-26.734 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.580)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.570)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.750)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.709)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">years_of_tenure_with_current_provider</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-13.611 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-13.724 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-15.524 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-14.700 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1.836)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(1.796)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(2.386)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(2.234)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">actual_change_in_price_vs_last_year</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.097 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.187 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.004)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.007)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">percent_change_in_price_vs_last_year</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">2.344 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">2.334 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">1.182 *&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.733&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.482)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.471)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.490)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.459)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">renewed</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-70.780 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-65.802 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-68.701 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-56.897 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.257)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.190)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(4.225)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.966)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">marital_status_d</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-77.135 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-76.146 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-80.901 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-72.199 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(11.805)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(11.549)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(15.080)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(14.119)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">marital_status_m</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-63.482 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-60.323 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-68.212 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-61.505 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(10.764)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(10.530)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(13.703)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(12.830)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">marital_status_s</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-46.404 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-42.282 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-53.400 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-43.438 **&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(11.240)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(10.997)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(14.328)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(13.416)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">marital_status_v</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-106.767 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-98.841 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-148.693 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-130.142 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(26.159)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(25.592)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(34.623)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(32.418)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">gender_f</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-67.977 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-66.156 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-67.883 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-62.240 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.184)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.115)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(4.120)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.860)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">payment_method_annual</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-60.124 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-58.926 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-61.064 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-59.850 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.782)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.700)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(4.889)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(4.577)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">acquisition_channel_inbound</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">34.557 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">35.432 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">35.996 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">39.512 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.939)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(3.853)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(5.095)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(4.771)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">actual_change_in_price_vs_last_year_pos</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.182 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.451 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.005)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.009)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">actual_change_in_price_vs_last_year_neg</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.058 ***</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-0.134 ***</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;"></th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.006)&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">(0.010)&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">N</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">20017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">20017&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">12010&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">12010&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">R2</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.311&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.340&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.324&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">0.407&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">logLik</th><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-136173.905&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-135733.824&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-81741.371&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">-80949.269&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">AIC</th><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">272379.811&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">271501.648&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">163514.743&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="vertical-align: top; text-align: right; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.8pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">161932.538&nbsp;&nbsp;&nbsp;&nbsp;</td></tr>
<tr>
<th colspan="5" style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.8pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;"> *** p &lt; 0.001;  ** p &lt; 0.01;  * p &lt; 0.05.</th></tr>
</table>

<pre class="r"><code>#finally, we compare the adjusted R-squared, MSE and MAE of a linear regression vs the weighted average of the linear regression which distriminate for the sign of the actual change in price vs last year
lin_reg_r2 &lt;- 0.3101
lin_reg_disc_r2 &lt;- 0.3398

mse_lin_reg_sig &lt;- format(round(unlist(as.numeric(mse_lin_reg_sig,0))), nsmall = 0)
mse_lin_reg_act_pric_disc &lt;- mse_lin_reg_act_pric_disc &lt;- format(round(unlist(as.numeric(mse_lin_reg_act_pric_disc,0))), nsmall = 0)
mae_lin_reg_sig &lt;- mae_lin_reg_sig &lt;- format(round(unlist(as.numeric(mae_lin_reg_sig,0))), nsmall = 0)
mae_lin_reg_act_pric_disc &lt;- mae_lin_reg_act_pric_disc &lt;- format(round(unlist(as.numeric(mae_lin_reg_act_pric_disc,0))), nsmall = 0)
mape_lin_reg_sig &lt;- mape_lin_reg_sig &lt;- format(round(unlist(as.numeric(mape_lin_reg_sig,0))), nsmall = 0)
mape_lin_reg_act_pric_disc &lt;- mape_lin_reg_act_pric_disc &lt;- format(round(unlist(as.numeric(mape_lin_reg_act_pric_disc,0))), nsmall = 0)

total_comparables &lt;- data.frame(cbind(lin_reg_r2,lin_reg_disc_r2))
total_comparables[nrow(total_comparables)+1,] &lt;- cbind(mse_lin_reg_sig,mse_lin_reg_act_pric_disc)
total_comparables[nrow(total_comparables)+1,] &lt;- cbind(mae_lin_reg_sig,mae_lin_reg_act_pric_disc)
total_comparables[nrow(total_comparables)+1,] &lt;- cbind(mape_lin_reg_sig,mape_lin_reg_act_pric_disc)
total_comparables[2,] &lt;- prettyNum(total_comparables[2,],big.mark=&quot;,&quot;,scientific=FALSE)

colnames(total_comparables) &lt;- c(&quot;Linear regression&quot;,&quot;Linear regression based on sign of actual price change (weighted average)&quot;)
rownames(total_comparables) &lt;- c(&quot;Ajudsted R-Square&quot;,&quot;Mean Square Error (back tested)&quot;,&quot;Mean Absolute Error (back tested)&quot;,&quot;Mean Absolute Percentage Error (back tested)&quot;)

metrics_names &lt;- rownames(total_comparables)
total_comparables &lt;- cbind(metrics_names,total_comparables)
colnames(total_comparables) &lt;- c(&quot;Metrics&quot;,&quot;Linear regression&quot;,&quot;Linear regression disc. for actual price change&quot;)

total_comparables</code></pre>
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:comparison of linear regressions">
<col><col><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Metrics</th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Linear regression</th><th style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: bold;">Linear regression disc. for actual price change</th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Ajudsted R-Square</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.3101</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0.4pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">0.3398</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Mean Square Error (back tested)</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">50,453</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">70,450</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">Mean Absolute Error (back tested)</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">137</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0pt 0pt;    padding: 6pt 6pt 6pt 6pt; background-color: rgb(242, 242, 242); font-weight: normal;">127</td></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0.4pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Mean Absolute Percentage Error (back tested)</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">34</td><td style="vertical-align: top; text-align: left; white-space: normal; border-style: solid solid solid solid; border-width: 0pt 0.4pt 0.4pt 0pt;    padding: 6pt 6pt 6pt 6pt; font-weight: normal;">30</td></tr>
</table>

<p>When looking at the tables, we see that regressing the price for the statistically significant variables gives us an adjusted R-squared of <strong>0.3101</strong>, vs <strong>0.3398</strong> when we use interaction terms. This is a <strong>9.58%</strong> improvement in the accuracy of our model.</p>
<p>This is to be expected because, as explained above, an increase in the actual change in price vs. last year has a negative effect on price when it is negative, but a positive impact when it is positive. The overall effect is positive, but running a linear regression without interaction terms “waters down” that effect. The coefficient for the actual change in price vs last year is indeed <strong>0.097</strong> overall, but <strong>0.182</strong> when positive and <strong>-0.058</strong> when negative.</p>
<p>When backtesting on <strong>40%</strong> of the data, we obtain a MAE and MAPE of respectively <strong>137</strong> and <strong>127</strong> without interaction terms and <strong>34</strong> and <strong>30</strong> with these terms. Interaction terms for the actual change in price therefore decreases MAE by <strong>7.3%</strong> and MAPE by <strong>11.76%</strong>.</p>
<p>Analyzing the data to a greater extent could help coming up with more interaction terms that could improve further the predictive power of our model.</p>
<p><strong>We conclude that our linear regression model with the interaction terms is the best one to predict movements in prices.</strong></p>
</div>
</div>
</div>
<div id="analyse-the-data-to-determine-the-factors-that-drive-the-renewal-rate" class="section level1">
<h1>3 Analyse the data to determine the factors that drive the renewal rate</h1>
<div id="create-the-logistic-regression-model" class="section level2">
<h2>3.1. Create the logistic regression model</h2>
<div id="create-the-model" class="section level3">
<h3>3.1.1. Create the model</h3>
<p>We create a logistic regression model.</p>
<pre class="r"><code>#create our logistic regression model
log_reg_full &lt;- glm(formula = renewed ~ age+
                  price+
                  car_value+
                  years_of_no_claims_bonus+
                  annual_mileage+
                  years_of_tenure_with_current_provider+
                  actual_change_in_price_vs_last_year+
                  percent_change_in_price_vs_last_year+
                  marital_status_d+
                  marital_status_m+
                  marital_status_s+
                  marital_status_v+
                  gender_f+
                  gender_m+
                  payment_method_annual+
                  acquisition_channel_aggreg+
                  acquisition_channel_direct+
                  acquisition_channel_inbound,
                data = insurance_data_dummied_short)
summary(log_reg_full)</code></pre>
<pre><code>## 
## Call:
## glm(formula = renewed ~ age + price + car_value + years_of_no_claims_bonus + 
##     annual_mileage + years_of_tenure_with_current_provider + 
##     actual_change_in_price_vs_last_year + percent_change_in_price_vs_last_year + 
##     marital_status_d + marital_status_m + marital_status_s + 
##     marital_status_v + gender_f + gender_m + payment_method_annual + 
##     acquisition_channel_aggreg + acquisition_channel_direct + 
##     acquisition_channel_inbound, data = insurance_data_dummied_short)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.1953  -0.5183   0.2588   0.3558   1.3255  
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                            3.901e-01  2.920e-01   1.336 0.181484
## age                                    2.289e-03  3.306e-04   6.923 4.56e-12
## price                                 -3.258e-04  1.499e-05 -21.734  &lt; 2e-16
## car_value                              3.443e-06  8.986e-07   3.831 0.000128
## years_of_no_claims_bonus              -1.971e-03  1.330e-03  -1.482 0.138341
## annual_mileage                        -3.703e-06  9.513e-07  -3.892 9.95e-05
## years_of_tenure_with_current_provider  2.368e-02  3.947e-03   6.000 2.01e-09
## actual_change_in_price_vs_last_year   -2.185e-05  8.199e-06  -2.665 0.007696
## percent_change_in_price_vs_last_year  -2.781e-03  1.033e-03  -2.691 0.007121
## marital_status_d                      -2.036e-02  2.537e-02  -0.802 0.422294
## marital_status_m                       1.057e-02  2.313e-02   0.457 0.647758
## marital_status_s                       2.479e-02  2.413e-02   1.027 0.304359
## marital_status_v                       1.372e-03  5.614e-02   0.024 0.980499
## gender_f                              -1.782e-01  1.048e-01  -1.701 0.089023
## gender_m                              -1.722e-01  1.047e-01  -1.644 0.100100
## payment_method_annual                 -2.404e-01  7.994e-03 -30.069  &lt; 2e-16
## acquisition_channel_aggreg             5.693e-01  3.018e-01   1.886 0.059291
## acquisition_channel_direct             4.542e-01  2.702e-01   1.681 0.092777
## acquisition_channel_inbound            4.604e-01  2.701e-01   1.704 0.088330
##                                          
## (Intercept)                              
## age                                   ***
## price                                 ***
## car_value                             ***
## years_of_no_claims_bonus                 
## annual_mileage                        ***
## years_of_tenure_with_current_provider ***
## actual_change_in_price_vs_last_year   ** 
## percent_change_in_price_vs_last_year  ** 
## marital_status_d                         
## marital_status_m                         
## marital_status_s                         
## marital_status_v                         
## gender_f                              .  
## gender_m                                 
## payment_method_annual                 ***
## acquisition_channel_aggreg            .  
## acquisition_channel_direct            .  
## acquisition_channel_inbound           .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 0.2185905)
## 
##     Null deviance: 4709.1  on 20016  degrees of freedom
## Residual deviance: 4371.4  on 19998  degrees of freedom
## AIC: 26390
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<pre class="r"><code>#predict contract renewal using our logigistic regression model trained on the whole dataset
predict_log_reg_full &lt;- predict(log_reg_full, newdata = insurance_data_dummied_short, type =&quot;response&quot;)
predict_log_reg_full_df &lt;- data.frame(predict_log_reg_full)

#combine predicted and actual renewal rates to plot a ROC curve and assess the efficiency of our model
renewed_from_full_sample &lt;- data.frame(insurance_data_dummied_short$renewed)
ROC_logreg_full &lt;- cbind(renewed_from_full_sample,predict_log_reg_full_df)
colnames(ROC_logreg_full) &lt;- c(&quot;actual_renewed&quot;,&quot;predicted_renewed&quot;)

#plot the ROC curve
PRROC_obj &lt;- roc.curve(scores.class0 = ROC_logreg_full$predicted_renewed, weights.class0=ROC_logreg_full$actual_renewed,
                       curve=TRUE)
plot(PRROC_obj)</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/logistic%20regression-1.png" width="672" /></p>
<p>We obtain an AUC of <strong>0.652</strong>, which means that our model performs better than a random classifier.</p>
</div>
<div id="back-test-the-model" class="section level3">
<h3>3.1.2. Back-test the model</h3>
<pre class="r"><code>#we now train our model on a sample of the dataset to back-test our logistic regression model (the same one we used for the backtesting of our linear regression models)
log_reg_full_trained &lt;- glm(formula = renewed ~ age+
                  price+
                  car_value+
                  years_of_no_claims_bonus+
                  annual_mileage+
                  years_of_tenure_with_current_provider+
                  actual_change_in_price_vs_last_year+
                  percent_change_in_price_vs_last_year+
                  marital_status_d+
                  marital_status_m+
                  marital_status_s+
                  marital_status_v+
                  gender_f+
                  gender_m+
                  payment_method_annual+
                  acquisition_channel_aggreg+
                  acquisition_channel_direct+
                  acquisition_channel_inbound,
                data = insurance_data_dummied_short_train)
summary(log_reg_full_trained)</code></pre>
<pre><code>## 
## Call:
## glm(formula = renewed ~ age + price + car_value + years_of_no_claims_bonus + 
##     annual_mileage + years_of_tenure_with_current_provider + 
##     actual_change_in_price_vs_last_year + percent_change_in_price_vs_last_year + 
##     marital_status_d + marital_status_m + marital_status_s + 
##     marital_status_v + gender_f + gender_m + payment_method_annual + 
##     acquisition_channel_aggreg + acquisition_channel_direct + 
##     acquisition_channel_inbound, data = insurance_data_dummied_short_train)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.8581  -0.5198   0.2584   0.3525   1.3006  
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                            3.887e-01  3.550e-01   1.095  0.27362
## age                                    1.968e-03  4.269e-04   4.610 4.07e-06
## price                                 -3.136e-04  1.930e-05 -16.251  &lt; 2e-16
## car_value                              3.141e-06  1.158e-06   2.712  0.00669
## years_of_no_claims_bonus              -2.297e-03  1.713e-03  -1.341  0.18007
## annual_mileage                        -3.673e-06  1.232e-06  -2.982  0.00287
## years_of_tenure_with_current_provider  2.828e-02  5.108e-03   5.537 3.15e-08
## actual_change_in_price_vs_last_year   -3.773e-05  1.542e-05  -2.448  0.01438
## percent_change_in_price_vs_last_year  -2.174e-03  1.047e-03  -2.076  0.03794
## marital_status_d                      -9.144e-03  3.230e-02  -0.283  0.77711
## marital_status_m                       1.125e-02  2.935e-02   0.383  0.70139
## marital_status_s                       3.191e-02  3.066e-02   1.041  0.29795
## marital_status_v                      -8.624e-02  7.404e-02  -1.165  0.24412
## gender_f                              -1.936e-01  1.211e-01  -1.599  0.10978
## gender_m                              -1.840e-01  1.210e-01  -1.521  0.12839
## payment_method_annual                 -2.321e-01  1.031e-02 -22.515  &lt; 2e-16
## acquisition_channel_aggreg             3.741e-01  3.696e-01   1.012  0.31140
## acquisition_channel_direct             4.681e-01  3.309e-01   1.415  0.15717
## acquisition_channel_inbound            4.731e-01  3.307e-01   1.430  0.15266
##                                          
## (Intercept)                              
## age                                   ***
## price                                 ***
## car_value                             ** 
## years_of_no_claims_bonus                 
## annual_mileage                        ** 
## years_of_tenure_with_current_provider ***
## actual_change_in_price_vs_last_year   *  
## percent_change_in_price_vs_last_year  *  
## marital_status_d                         
## marital_status_m                         
## marital_status_s                         
## marital_status_v                         
## gender_f                                 
## gender_m                                 
## payment_method_annual                 ***
## acquisition_channel_aggreg               
## acquisition_channel_direct               
## acquisition_channel_inbound              
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 0.2183957)
## 
##     Null deviance: 2815.2  on 12009  degrees of freedom
## Residual deviance: 2618.8  on 11991  degrees of freedom
## AIC: 15831
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<pre class="r"><code>#we then predict contract renewal on the testing dataset using our model trained on the training dataset
predict_log_reg_test &lt;- predict(log_reg_full_trained, newdata = insurance_data_dummied_short_test, type =&quot;response&quot;)
predict_log_reg_test_df &lt;- data.frame(predict_log_reg_test)
renewed_from_testing_sample &lt;- data.frame(insurance_data_dummied_short_test$renewed)

#we combine predicted and actual values of contract renewal
ROC_logreg_test &lt;- cbind(renewed_from_testing_sample,predict_log_reg_test_df)
colnames(ROC_logreg_test) &lt;- c(&quot;actual_renewed&quot;,&quot;predicted_renewed&quot;)

#plot the curve
PRROC_obj &lt;- roc.curve(scores.class0 = ROC_logreg_test$predicted_renewed, weights.class0=ROC_logreg_test$actual_renewed,
                       curve=TRUE)
plot(PRROC_obj)</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/logistic%20regression%20test-1.png" width="672" /></p>
<p>Our AUC is <strong><em>0.654</em></strong> when back-testing on 40% of the data, which is close to the AUC we obtained using the whole dataset to train our model. Therefore, we can conclude that our logistic regression performs significantly better than a random classifier.</p>
</div>
</div>
<div id="determine-the-optimal-cut-off-point" class="section level2">
<h2>3.2. Determine the optimal cut-off point</h2>
<p>We know want to determine the best cut-off point to forecast renewal rates in a binary fashion. Among the several ways of doing this, we choose to use the Youden index (sensivity + specificity - 1), as we do not have any reason to favour sensivity over specificity (or the opposite).</p>
<pre class="r"><code>#creatin a function to dynamically embed the confusion matrix results in the youden formula
youden_function &lt;- function(x){
      predicted &lt;- data.frame(ifelse(predict_log_reg_full_df &gt; x, 1, 0))
      actual &lt;- data.frame(insurance_data_dummied_short$renewed)
      colnames(actual) &lt;- c(&quot;actual&quot;)
      colnames(predicted) &lt;- c(&quot;predicted&quot;)
    confusion_matrix &lt;- data.frame(table(actual$actual, predicted$predicted))
youden(confusion_matrix[4,3],confusion_matrix[3,3],confusion_matrix[1,3],confusion_matrix[2,3])
}

#creating a loop to compute the youden index for different cut-off points
youden_output &lt;- character()          
  for(i in seq(from=0, to=1, by=0.0125)) {             
    print_youden &lt;- youden_function(i)
    youden_output &lt;- c(youden_output, print_youden)    
  }
youden_output &lt;- data.frame(as.numeric(youden_output))

#creating a loop to store the cut-off increments used so as to plot them
youden_increments &lt;- character()          
  for(i in seq(from=0, to=1, by=0.0125)) {             
    print_increments &lt;- i
    youden_increments &lt;- c(youden_increments, print_increments)    
  }
youden_increments &lt;- data.frame(as.numeric(youden_increments))

#creating a data frame with youden statistics and corresponding cut-off point increments
youden_cutoffs &lt;- cbind(youden_output,youden_increments)
colnames(youden_cutoffs) &lt;- c(&quot;youden&quot;,&quot;cut_off&quot;)

#determine the maximum youden statistic and the corresponding cut-off point
max_youden &lt;- max(youden_cutoffs$youden)
cut_off_for_max_youden &lt;- youden_cutoffs$cut_off[youden_cutoffs$youden == max_youden]

#plot our results
ggplot(youden_cutoffs, aes(x = cut_off, y = youden))+
  geom_line()+
  theme_bw()+
  geom_segment(aes(x = 0, y = max_youden, xend = cut_off_for_max_youden, yend = max_youden, colour=&quot;red&quot;))+
  geom_segment(aes(x = cut_off_for_max_youden, y = 0, xend = cut_off_for_max_youden, yend = max_youden, colour=&quot;blue&quot;))+
  labs(x=&quot;Cut-off&quot;,y=&quot;Youden&#39;s J Statistic&quot;,title=&quot;Youden&#39;s J Statistic vs. cut-off&quot;)+
  scale_color_hue(labels = c(&quot;Cut-off for max. Youden (0.5625)&quot;, &quot;Max. Youden (0.2177)&quot;))+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(legend.title=element_blank())</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/determining%20the%20optimal%20cut-off%20for%20our%20logistic%20regression%20model-1.png" width="672" /></p>
<p>The cut-off point for which the Youden Index is the highest is <strong>0.5625</strong>.</p>
</div>
</div>
<div id="maximise-profit-andor-revenue-by-changing-the-price" class="section level1">
<h1>4. Maximise profit and/or revenue by changing the price</h1>
<div id="determine-the-prices-that-maximize-revenue-and-profit" class="section level2">
<h2>4.1. Determine the prices that maximize revenue and profit</h2>
<div id="investigating-for-clustering" class="section level3">
<h3>4.1.1. Investigating for clustering</h3>
<p>We now would like to find the prices that maximize respectively profit and revenue. To that end, we will use the logistic regression model with the cut-off point we determined to predict the renewal rate according to different price levels.</p>
<p>First, we try to determine if your data can be clustered: maybe customer groups with different characteristics or habits can be determined. If such groups exist, they may have different sensivities to changes in price: we could then find the optimal</p>
<pre class="r"><code>#getting rid of the additional variables we added previously
insurance_data_dummied_short_clustering &lt;- insurance_data_dummied_short[,1:19]

#compute within cluster sum of squared distances
wss &lt;- function(k) {
  kmeans(insurance_data_dummied_short_clustering, k, nstart = 10 )$tot.withinss
}

#plot the sse by nu;ber of clusters between 1 and 15
k.values &lt;- 1:15
  wss_values &lt;- map_dbl(k.values, wss)
  plot(k.values, wss_values,
         type=&quot;b&quot;, pch = 19, frame = FALSE, 
         xlab=&quot;Number of clusters K&quot;,
         ylab=&quot;Total within-clusters sum of squares&quot;)</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/cluster%20the%20data-1.png" width="672" /></p>
<pre class="r"><code>#set number of clusters
k2 &lt;- kmeans(insurance_data_dummied_short_clustering, centers = 2, nstart = 25)
k3 &lt;- kmeans(insurance_data_dummied_short_clustering, centers = 3, nstart = 25)
k4 &lt;- kmeans(insurance_data_dummied_short_clustering, centers = 4, nstart = 25)
k5 &lt;- kmeans(insurance_data_dummied_short_clustering, centers = 5, nstart = 25)

#create plots to compare clustering for different types of clusters
p1 &lt;- fviz_cluster(k2, geom = &quot;point&quot;, data = insurance_data_dummied_short_clustering) + ggtitle(&quot;k = 2&quot;)
p2 &lt;- fviz_cluster(k3, geom = &quot;point&quot;,  data = insurance_data_dummied_short_clustering) + ggtitle(&quot;k = 3&quot;)
p3 &lt;- fviz_cluster(k4, geom = &quot;point&quot;,  data = insurance_data_dummied_short_clustering) + ggtitle(&quot;k = 4&quot;)
p4 &lt;- fviz_cluster(k5, geom = &quot;point&quot;,  data = insurance_data_dummied_short_clustering) + ggtitle(&quot;k = 5&quot;)
grid.arrange(p1, p2, p3, p4, nrow = 2)</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/cluster%20the%20data-2.png" width="672" /></p>
<pre class="r"><code>#examine the distance to the center of the variables for each cluster
res_kmeans &lt;- cluster_analysis(insurance_data_dummied_short_clustering,
                 n = 2,
                 method = &quot;kmeans&quot;)

#predict the centers
predict(res_kmeans)</code></pre>
<pre class="r"><code>#plot the centers
plot(summary(res_kmeans))</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/plot%20cluster%20the%20data-1.png" width="672" /></p>
<p>As we can see on the charts, there seems to be no cluster: they are all pretty similar and cover the same data points; even when examining for only two clusters, we cannot notice any significant difference between different subgroups of our population. It would thus be not relevant to cluster our data, as it would not improve our ability to determine the best prices to maximize revenue or profit.</p>
</div>
<div id="determining-the-prices-that-maximize-revenue-and-profit" class="section level3">
<h3>4.1.2. Determining the prices that maximize revenue and profit</h3>
<p>Since no relevant clustering can be performed, we will examine how uniform changes in price affect contract renewal (demand). We proceed as follows:
- We compute revenue as being the sum of the contracts’ prices when they are renewed
- We assume a cost per contract (variable cost), which is incurred only for renewed contracts
- We assume fixed costs that are incurred by the insurance company
- We examine the effect of uniform increases or decreases (i.e. we increase or increase all the prices by increment of 12.5bps).</p>
<pre class="r"><code>#set our assumptions
cost_per_contract = 200
fixed_costs = 900000
increment = 0.0125 #examining the effect of price changes by increment of 12.5 bps

#compute actual revenue, profit and number of contracts sold
insurance_data_dummied_short$next_y_revenue = insurance_data_dummied_short$price*insurance_data_dummied_short$renewed
insurance_data_dummied_short$cost_per_contract = cost_per_contract
insurance_data_dummied_short$next_y_profit = insurance_data_dummied_short$next_y_revenue - insurance_data_dummied_short$cost_per_contract*insurance_data_dummied_short$renewed
next_year_revenue = sum(insurance_data_dummied_short$next_y_revenue)
next_year_revenue &lt;- round(next_year_revenue/1000, digits = 0)
next_y_profit = sum(insurance_data_dummied_short$next_y_profit) - fixed_costs
next_y_profit &lt;- round(next_y_profit/1000, digits = 0)
next_y_contracts_sold = sum(insurance_data_dummied_short$renewed)
next_y_contracts_sold &lt;- round(next_y_contracts_sold, digits = 0)

#set new data frame to create our functions
insurance_data_dummied_new &lt;- insurance_data_dummied_short

#create a function to predict the number of new contracts sold following changes in price
contracts_sold &lt;- function(x){
  insurance_data_dummied_new$price &lt;- insurance_data_dummied_new$price*(1+x)
    predict_new &lt;- data.frame(predict(log_reg_full, newdata = insurance_data_dummied_new, type =&quot;response&quot;))
    colnames(predict_new) &lt;- &quot;prediction&quot;
    predict_new &lt;- data.frame(ifelse(predict_new$prediction &lt; cut_off_for_max_youden,0,1))
    predict_new &lt;- cbind(insurance_data_dummied_new$price,predict_new)
    colnames(predict_new) &lt;- c(&quot;price&quot;,&quot;renewed&quot;)
  no_contract_sold = sum(predict_new$renewed)
  no_contract_sold
}

#create a function to predict revenue following changes in price
price_change &lt;- function(x){
  insurance_data_dummied_new$price &lt;- insurance_data_dummied_new$price*(1+x)
    predict_new &lt;- data.frame(predict(log_reg_full, newdata = insurance_data_dummied_new, type =&quot;response&quot;))
    colnames(predict_new) &lt;- &quot;prediction&quot;
    predict_new &lt;- data.frame(ifelse(predict_new$prediction &lt; cut_off_for_max_youden,0,1))
    predict_new &lt;- cbind(insurance_data_dummied_new$price,predict_new)
    colnames(predict_new) &lt;- c(&quot;price&quot;,&quot;renewed&quot;)
    predict_new$next_y_revenue &lt;- predict_new$price*predict_new$renewed
  next_year_revenue_new = sum(predict_new$next_y_revenue)
  next_year_revenue_new
}

#create function to predict change in profit following changes in price
profit_change &lt;- function(x){
  insurance_data_dummied_new$price &lt;- insurance_data_dummied_new$price*(1+x)
    predict_new &lt;- data.frame(predict(log_reg_full, newdata = insurance_data_dummied_new, type =&quot;response&quot;))
    colnames(predict_new) &lt;- &quot;prediction&quot;
    predict_new &lt;- data.frame(ifelse(predict_new$prediction &lt; cut_off_for_max_youden,0,1))
    predict_new &lt;- cbind(insurance_data_dummied_new$price,predict_new)
    colnames(predict_new) &lt;- c(&quot;price&quot;,&quot;renewed&quot;)
    predict_new$next_y_revenue &lt;- predict_new$price*predict_new$renewed
    predict_new$next_y_profit &lt;- predict_new$price*predict_new$renewed - cost_per_contract*predict_new$renewed
next_year_profit = sum(predict_new$next_y_profit) - fixed_costs
next_year_profit
}

#create loop to predict number of new contracts following change in price using the function created before to that end
no_contracts_sold &lt;- character() 
for(i in seq(from=-1, to=6, by=increment)) {             
  no_contracts_sold_output &lt;- contracts_sold(i)
  no_contracts_sold &lt;- c(no_contracts_sold, no_contracts_sold_output)    
}
no_contracts_sold &lt;- data.frame(as.numeric(no_contracts_sold))

#create loop to predict revenue following change in price using the function created before to that end
price_change_output &lt;- character() 
for(i in seq(from=-1, to=6, by=increment)) {             
  print_price_change &lt;- price_change(i)
  price_change_output &lt;- c(price_change_output, print_price_change)    
}
price_change_output &lt;- data.frame(as.numeric(price_change_output))

#create loop to predict profit following change in price using the function created before to that end
profit_change_output &lt;- character() 
for(i in seq(from=-1, to=6, by=increment)) {             
  print_profit_change &lt;- profit_change(i)
  profit_change_output &lt;- c(profit_change_output, print_profit_change)    
}
profit_change_output &lt;- data.frame(as.numeric(profit_change_output))

#create loop to print changes in price
price_change_imcrement &lt;- character() 
for(i in seq(from=-1, to=6, by=increment)) {             
  print_price_tics &lt;- i
  price_change_imcrement &lt;- c(price_change_imcrement, print_price_tics)    
}
price_change_imcrement &lt;- data.frame(as.numeric(price_change_imcrement))

#create a table to compare revenue, profit and number of contracts sold per increment of price change
forecast &lt;- data.frame(cbind(price_change_imcrement,no_contracts_sold,price_change_output,profit_change_output))
colnames(forecast) &lt;- c(&quot;change_in_price&quot;,&quot;number_of_contracts_sold&quot;,&quot;Revenue&quot;,&quot;Profit&quot;)
forecast$Revenue &lt;- round(forecast$Revenue/1000, digits = 0)
forecast$Profit &lt;- round(forecast$Profit/1000, digits = 0)

#save values of maximum revenue and corresponding price
max_revenue &lt;- max(forecast$Revenue)
price_max_revenue &lt;- forecast$change_in_price[forecast$Revenue == max_revenue]

#save values of maximum profit and corresponding price
max_profit &lt;- max(forecast$Profit)
price_max_profit &lt;- forecast$change_in_price[forecast$Profit == max_profit]

#save value of minimum profit and price and maximum price which will be the extrema of the lines of our plot
min_profit &lt;- min(forecast$Profit)
min_price &lt;- min(forecast$change_in_price)
max_price &lt;- max(forecast$change_in_price)

#create the dynamic title of our chart
fixed_costs_char &lt;- prettyNum(fixed_costs,big.mark=&quot;,&quot;,scientific=FALSE)
variable_costs_char &lt;- prettyNum(fixed_costs,big.mark=&quot;,&quot;,scientific=FALSE)
title_1 &lt;- &quot;Predicted revenue and profit vs. price change for \nfixed costs of £&quot;
title_2 &lt;- &quot;and cost per contract of £&quot;
title_full &lt;- paste(title_1, fixed_costs_char, title_2, cost_per_contract)

#create the dynamic legend for the predicted revenue segments of our chart
max_revenue_1 &lt;- &quot;Maximum revenue of £&quot;
max_revenue_2 &lt;- prettyNum(max_revenue,big.mark=&quot;,&quot;,scientific=FALSE)
max_revenue_3 &lt;- &quot;K\nfor a price increase of&quot;
max_revenue_4 &lt;- price_max_revenue*100
max_revenue_5 &lt;- &quot;%&quot;
max_rev_full &lt;- paste(max_revenue_1, max_revenue_2, max_revenue_3, max_revenue_4, max_revenue_5)

#create the dynamic legend for the predicted profit segments of our chart
max_profit_1 &lt;- &quot;Maximum profit of £&quot;
max_profit_2 &lt;- prettyNum(max_profit, big.mark=&quot;,&quot;, scientific=FALSE)
max_profit_3 &lt;- &quot;K\nfor a price increase of&quot;
max_profit_4 &lt;- price_max_profit*100
max_profit_5 &lt;- &quot;%&quot;
max_profit_full &lt;- paste(max_profit_1, max_profit_2, max_profit_3, max_profit_4, max_profit_5)

#create the dynamic legend for the actual revenue line of our chart
actual_rev_1 &lt;- &quot;Actual revenue of £&quot;
actual_rev_2 &lt;- prettyNum(next_year_revenue, big.mark=&quot;,&quot;, scientific=FALSE)
actual_rev_3 &lt;- &quot;K&quot;
actual_rev_full &lt;- paste(actual_rev_1, actual_rev_2, actual_rev_3)

#create the dynamic legend for the actual profit line of our chart
acual_profit_1 &lt;- &quot;Actual profit of £&quot;
acual_profit_2 &lt;- prettyNum(next_y_profit, big.mark=&quot;,&quot;, scientific=FALSE)
actual_profit_3 &lt;- &quot;K&quot;
actual_profit_full &lt;- paste(acual_profit_1, acual_profit_2, actual_profit_3)

#pivot our forecast table to plot to create our chart
forecast_2 &lt;- data_frame(forecast[,c(&quot;change_in_price&quot;,&quot;Revenue&quot;,&quot;Profit&quot;)])</code></pre>
<pre><code>## Warning: `data_frame()` was deprecated in tibble 1.1.0.
## Please use `tibble()` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.</code></pre>
<pre class="r"><code>forecast_2 &lt;- pivot_longer(forecast_2, !change_in_price, names_to = &quot;effect&quot;, values_to = &quot;values&quot;)

#create our chart plotting predicted revenue and predicted profit for changes in price and actual revenue and actual profit for comparison
ggplot(forecast_2, aes(y=values, x=change_in_price))+
  geom_line(aes(color = effect), size = 1.15)+
  geom_segment(aes(x = min_price, y = max_revenue, xend = price_max_revenue, yend = max_revenue, color = max_rev_full), size = 1, linetype = 1)+
  geom_segment(aes(x = price_max_revenue, y = min_profit, xend = price_max_revenue, yend = max_revenue, color = max_rev_full), size = 1, linetype = 1)+
  geom_segment(aes(x = min_price, y = max_profit, xend = price_max_profit, yend = max_profit, color = max_profit_full), size = 1, linetype = 1)+
  geom_segment(aes(x = price_max_profit, y = min_profit, xend = price_max_profit, yend = max_profit, color = max_profit_full), size = 1, linetype = 1)+
  geom_segment(aes(x = min_price, y = next_year_revenue, xend = max_price, yend = next_year_revenue, color = actual_rev_full), size = 1, linetype = 2)+
  geom_segment(aes(x = min_price, y = next_y_profit, xend = max_price, yend = next_y_profit, color = actual_profit_full), size = 1, linetype = 2)+
  scale_color_manual(values = c(&quot;#60B56D&quot;, &quot;#9FA2DE&quot;, &quot;#008614&quot;, &quot;#030CD1&quot;, &quot;#888897&quot;, &quot;#53545E&quot;))+
  theme_classic()+
  labs(title = c(title_full), y = &quot;Amount (&#39;000s £)&quot;, x = &quot;Change in price (&#39;00s %)&quot; )+
  theme(legend.title=element_blank())</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/determination%20of%20the%20prices%20that%20respectively%20maximize%20revenue%20and%20profit-1.png" width="672" />
According to our logistic regression model and our optimal cut-off point, assuming a cost per contract of <strong>£200</strong> and fixed costs of <strong>£9,000K</strong>:
- A maximum revenue of <strong>£5,494K</strong> could be reached with a <strong>30%</strong> price increase, which would be a <strong>12.8%</strong> improvement over the current revenue of <strong>£4,871K</strong>
- A maximum profit of <strong>£2,280K</strong> could be reached with a <strong>48.75%</strong> price increase, which would be a <strong>53.74%</strong> improvement over the current profit of <strong>£1,483K</strong></p>
<p><em>Note: the actual revenue and profit lines do not intersect with the forecast curves and y = 0 because the curves correspond to forecast values that differ from the actual values.</em></p>
</div>
</div>
<div id="examine-the-effects-of-price-changes-on-volume-and-compute-the-elasticity-of-demand-renewal-rate-to-price" class="section level2">
<h2>4.2. Examine the effects of price changes on volume and compute the elasticity of demand (renewal rate) to price</h2>
<p>We then examine the effect on demand of changes in price and determine the price elasticity of demand (contract renewal rate).</p>
<pre class="r"><code>#create a table to plot the change in number of contract sold following changes in price
forecast_3 &lt;- data_frame(forecast[,c(&quot;change_in_price&quot;,&quot;number_of_contracts_sold&quot;)])

#create a dynamic title for our chart
title_no_contracts_1 &lt;- &quot;Predicted number of contracts sold vs. price change for\nfixed costs of £&quot;
title_no_contracts_2 &lt;- &quot;and cost per contract of £&quot;
title_no_contracts_full &lt;- paste(title_no_contracts_1, fixed_costs_char, title_no_contracts_2, cost_per_contract)

#print quantities for respectively the maximum revenue and maximum profit that can be obtained through changing the price according to our model
qty_max_revenue &lt;- forecast$number_of_contracts_sold[forecast$Revenue == max_revenue]
qty_max_profit &lt;- forecast$number_of_contracts_sold[forecast$Profit == max_profit]

#create the dynamic legend for the predicted revenue segments of our chart
qty_prof_max_1 &lt;- &quot;Maximum profit of £&quot;
qty_prof_max_2 &lt;- prettyNum(max_profit,big.mark=&quot;,&quot;,scientific=FALSE)
qty_prof_max_3 &lt;- &quot;K\nfor a number of contracts sold of&quot;
qty_prof_max_4 &lt;- prettyNum(qty_max_profit,big.mark=&quot;,&quot;,scientific=FALSE)
qty_prof_max_full &lt;- paste(qty_prof_max_1, qty_prof_max_2, qty_prof_max_3, qty_prof_max_4)

#create the dynamic legend for the predicted revenue segments of our chart
qty_rev_max_1 &lt;- &quot;Maximum revenue of £&quot;
qty_rev_max_2 &lt;- prettyNum(max_revenue,big.mark=&quot;,&quot;,scientific=FALSE)
qty_rev_max_3 &lt;- &quot;K\nfor a number of contracts sold of&quot;
qty_rev_max_4 &lt;- prettyNum(qty_max_revenue,big.mark=&quot;,&quot;,scientific=FALSE)
qty_rev_max_full &lt;- paste(qty_rev_max_1, qty_rev_max_2, qty_rev_max_3, qty_rev_max_4)

#create the dynamic legend for the predicted revenue segments of our chart
qty_act_1 &lt;- &quot;Actual number of contracts sold of&quot;
qty_act_2 &lt;- prettyNum(next_y_contracts_sold,big.mark=&quot;,&quot;,scientific=FALSE)
qty_act_full &lt;- paste(qty_act_1, qty_act_2)

#plot our chart showing the number of contracts sold for the prices which respectively maximize the revenue and the profit
ggplot(forecast_3, aes(y=number_of_contracts_sold, x=change_in_price))+
  geom_line(aes(color = &quot;Number of contracts sold&quot;), size = 1.15)+
  geom_segment(aes(x = min_price, y = qty_max_revenue, xend = price_max_revenue, yend = qty_max_revenue, color = qty_rev_max_full), size = 1, linetype = 1)+
  geom_segment(aes(x = price_max_revenue, y = 0, xend = price_max_revenue, yend = qty_max_revenue, color = qty_rev_max_full), size = 1, linetype = 1)+
  geom_segment(aes(x = min_price, y = qty_max_profit, xend = price_max_profit, yend = qty_max_profit, color = qty_prof_max_full), size = 1, linetype = 1)+
  geom_segment(aes(x = price_max_profit, y = 0, xend = price_max_profit, yend = qty_max_profit, color = qty_prof_max_full), size = 1, linetype = 1)+
  geom_segment(aes(x = min_price, y = next_y_contracts_sold, xend = max_price, yend = next_y_contracts_sold, color = qty_act_full), size = 1, linetype = 2)+
  scale_color_manual(values = c(&quot;#E79292&quot;, &quot;#008614&quot;, &quot;#030CD1&quot;, &quot;#53545E&quot;))+
  labs(title = c(title_no_contracts_full), y = &quot;Number of contracts sold&quot;, x = &quot;Change in price (&#39;00s %)&quot; )+
  theme_classic()+
  theme(legend.title=element_blank())</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/determine%20impact%20on%20volumes%20for%20prices%20obtained%20above-1.png" width="672" /></p>
<p>We can observe that maximizing revenue through a <strong>30%</strong> price increase would reduce the number of contract renewed by <strong>3.64%</strong>, whereas maximizing profit through a <strong>48.75%</strong> price increase would reduce it by <strong>13.95%</strong>.</p>
<p>We then fit a curve to our forecast of the number of contracts renewed vs. price changes, so as to determine a demand function with which we will determine the price elasticity of demand.</p>
<pre class="r"><code>#create different fitting curves
cont_1 &lt;- lm(number_of_contracts_sold ~ poly(change_in_price, 1, raw = TRUE), forecast_3)
cont_2 &lt;- lm(number_of_contracts_sold ~ poly(change_in_price, 2, raw = TRUE), forecast_3)
cont_3 &lt;- lm(number_of_contracts_sold ~ poly(change_in_price, 3, raw = TRUE), forecast_3)
cont_4 &lt;- lm(number_of_contracts_sold ~ poly(change_in_price, 4, raw = TRUE), forecast_3)

#store the curves values in dataset
pred_cont_1 &lt;- data.frame(predict(cont_1, newdata = forecast_3))
pred_cont_2 &lt;- data.frame(predict(cont_2, newdata = forecast_3))
pred_cont_3 &lt;- data.frame(predict(cont_3, newdata = forecast_3))
pred_cont_4 &lt;- data.frame(predict(cont_4, newdata = forecast_3))
colnames(pred_cont_1) &lt;- &quot;fit_no_contracts_sold_1&quot;
colnames(pred_cont_2) &lt;- &quot;fit_no_contracts_sold_2&quot;
colnames(pred_cont_3) &lt;- &quot;fit_no_contracts_sold_3&quot;
colnames(pred_cont_4) &lt;- &quot;fit_no_contracts_sold_4&quot;

#compare the values of our fitting curves to the values of our forecast
pred_cont_full &lt;- data.frame(cbind(forecast_3$change_in_price, 
                                   forecast_3$number_of_contracts_sold, 
                                   pred_cont_1$fit_no_contracts_sold_1,
                                   pred_cont_2$fit_no_contracts_sold_2,
                                   pred_cont_3$fit_no_contracts_sold_3,
                                   pred_cont_4$fit_no_contracts_sold_4))
colnames(pred_cont_full) &lt;- c(&quot;price_change&quot;, &quot;Actual&quot;, &quot;Linear&quot;, &quot;Quadratic&quot;, &quot;Cubic&quot;, &quot;Quartic&quot;)
pred_cont_full &lt;- pivot_longer(pred_cont_full, !price_change, names_to = &quot;type&quot;, values_to = &quot;values&quot;)

#plot our forecast and the associated values
ggplot(pred_cont_full, aes(x = price_change, y = values, color = type))+
  geom_line(aes(color = type))+
  scale_linetype_manual(values = c(&quot;test&quot; = 2, &quot;dashed&quot; = 1, &quot;#dashed&quot; = 1, &quot;dashed&quot; = 1, &quot;dashed&quot; = 1))+
  labs(title = &quot;Prediction of number of contract sold vs. fitting curves&quot;, y = &quot;Number of contracts sold&quot;, x = &quot;Change in price (&#39;00s %)&quot; )+
  theme_classic()+
  theme(legend.title=element_blank())</code></pre>
<p><img src="/projects/price_optimisation_files/figure-html/curve%20fitting%20on%20our%20forecast%20of%20the%20number%20of%20contracts%20renewed-1.png" width="672" /></p>
<pre class="r"><code>summary(cont_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = number_of_contracts_sold ~ poly(change_in_price, 
##     2, raw = TRUE), data = forecast_3)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1153.07  -487.74    42.17   495.38   790.84 
## 
## Coefficients:
##                                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                           13049.828     36.832   354.3   &lt;2e-16 ***
## poly(change_in_price, 2, raw = TRUE)1 -5993.117     31.544  -190.0   &lt;2e-16 ***
## poly(change_in_price, 2, raw = TRUE)2   669.165      5.932   112.8   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 515 on 558 degrees of freedom
## Multiple R-squared:  0.9925, Adjusted R-squared:  0.9924 
## F-statistic: 3.674e+04 on 2 and 558 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#create a demand function based on the coefficients of our second fitting curve
demand_function &lt;- function(x) {13049.828 - 5993.117*x + 669.165 * x ^2}

#compute the price-elasticity of demand
no_price_change_demand &lt;- demand_function(0)
plus_one_percent_demand &lt;- demand_function(0.01)
minus_one_percent_demand &lt;- demand_function(-0.01)
price_increase_impact &lt;- ((plus_one_percent_demand - no_price_change_demand)/no_price_change_demand)/0.01
price_decrease_impact &lt;- ((minus_one_percent_demand - no_price_change_demand)/no_price_change_demand)/-0.01
elast_price_inc &lt;- price_increase_impact
elast_price_desc &lt;- price_decrease_impact
elast_price_inc</code></pre>
<pre><code>## [1] -0.458736</code></pre>
<pre class="r"><code>elast_price_desc</code></pre>
<pre><code>## [1] -0.4597615</code></pre>
<p>We can see from the chart that a quadratic equation is good enough to create a fitting demand function. We use this demand function to compute the price elasticity of demand, and we find that it is <strong>-0.4587</strong> for a 1% price increase and <strong>-0.4597</strong> for a 1% price decrease from our current price. This means that demand is relatively inelastic to price (|price elasticity of demand| &lt; 1).</p>
</div>
</div>
